### PR TITLE
Theme example files

### PR DESCRIPTION
**Pull request by pierrejochem**
This will help to create own themes for owncloud

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by karlitschek** [comment]
I think it is a good idea to ship with a very simple default example theme. I like this.
Not so sure about the use images. ;-)
What do you think @jancborchardt ?

**Comment by pierrejochem** [comment]
@karlitschek The images are only placeholders of course ;-)

**Comment by MorrisJobke** [comment]
@pierrejochem I guess it's more of "what is the license of them" or am I wrong?

**Comment by pierrejochem** [comment]
I'm not sure with the licence :-( I found it here: https://dribbble.com/shots/306193-Cloud-Drive and added the TUX to it but I can provide others which are 100% free to use with a link to the licence.

**Comment by karlitschek** [comment]
I like it. And I would like to add to the next release. But we need some partly decent images ;-)
@jancborchardt what do you think?

**Comment by pierrejochem** [comment]
I've added comments to the css to make it easier to understand and will publish it in the next days.

**Comment by jancborchardt** [comment]
@pierrejochem hey Pierre – due to the non-freely licensed images as well as the typeface it’s difficult to accept this. :\

I went ahead and made a very simple example theme, to review at https://github.com/owncloud/core/pull/16519
I figured it would also be best and cleanest if I do this since I wrote most of the CSS and know what needs to be changed.

**Comment by pierrejochem** [comment]
Looks perfect for me :+1:

**Pull request closed without merging**
